export * from './app/app.component';
export * from './collection/collection.component';
export * from './wantlist/wantlist.component';
export * from './sales/sales.component';
export * from './view-detail/view-detail.component';
export * from './selected-detail/selected-detail.component';
export * from './player/player.component';
export * from './search/search.component';
export * from './search-results/search-results.component';
